//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineLearningSystem.Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class assignment
    {
        public assignment()
        {
            this.student_assignment = new HashSet<student_assignment>();
        }
    
        public int id { get; set; }
        public string assignmentname { get; set; }
        public System.DateTime startdate { get; set; }
        public System.DateTime enddate { get; set; }
        public int teacherid { get; set; }
        public string filename { get; set; }
        public string description { get; set; }
        public string schoolid { get; set; }
        public string resources { get; set; }
        public string question1 { get; set; }
        public string question2 { get; set; }
        public string question3 { get; set; }
        public string question4 { get; set; }
        public string question5 { get; set; }
    
        public virtual ICollection<student_assignment> student_assignment { get; set; }
    }
}
