//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineLearningSystem.Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class review
    {
        public int id { get; set; }
        public int teacherid { get; set; }
        public int stars { get; set; }
        public int studentid { get; set; }
    
        public virtual review review1 { get; set; }
        public virtual review review2 { get; set; }
    }
}
