//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineLearningSystem.Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class student_assignment
    {
        public int id { get; set; }
        public int assignment_id { get; set; }
        public int student_id { get; set; }
    
        public virtual assignment assignment { get; set; }
        public virtual user_info user_info { get; set; }
    }
}
