//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineLearningSystem.Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_info
    {
        public user_info()
        {
            this.student_assignment = new HashSet<student_assignment>();
            this.student_info = new HashSet<student_info>();
            this.teacher_info = new HashSet<teacher_info>();
        }
    
        public int id { get; set; }
        public string username { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string password { get; set; }
        public string usertype { get; set; }
        public Nullable<System.DateTime> startdate { get; set; }
        public Nullable<System.DateTime> enddate { get; set; }
        public int schoolid { get; set; }
    
        public virtual ICollection<student_assignment> student_assignment { get; set; }
        public virtual ICollection<student_info> student_info { get; set; }
        public virtual ICollection<teacher_info> teacher_info { get; set; }
    }
}
